// version.h
// This file is automatically generated by CreateVersionFile.py

#define AVG_VERSION_RELEASE     "1.8.2"
#define AVG_VERSION_FULL        "1.8.2-master/c8709ab5856a777e6fb19d0c0b9d6dbe4631bbe8"
#define AVG_VERSION_BUILDER     "bhavesh@bhavesh Linux-5.0.0-27-generic-x86_64-with-Ubuntu-18.04-bionic"
#define AVG_VERSION_BUILDTIME   "2019-10-17T18:45:14.137297"
#define AVG_VERSION_REVISION    "c8709ab5856a777e6fb19d0c0b9d6dbe4631bbe8"
#define AVG_VERSION_MAJOR       "1"
#define AVG_VERSION_MINOR       "8"
#define AVG_VERSION_MICRO       "2"
